# Generated by Django 2.2.12 on 2020-11-26 09:24

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='başlık')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='ingilizce başlık')),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='rusça başlık')),
                ('price', models.IntegerField(verbose_name='fiyat')),
                ('detail', models.CharField(max_length=200, verbose_name='detay')),
                ('img', sorl.thumbnail.fields.ImageField(upload_to='urunler', verbose_name='resim')),
                ('desen', models.CharField(blank=True, choices=[('ekose', 'ekose'), ('Etnik', 'Etnik'), ('Geometrik', 'Geometrik'), ('Baliksirti', 'Baliksirti'), ('Kazayagi', 'Kazayagi'), ('Duz', 'Duz'), ('Cizgi', 'Cizgi'), ('Tweed', 'Tweed')], max_length=100, null=True)),
                ('renk', models.CharField(blank=True, choices=[('Bej', 'Bej'), ('Siyah', 'Siyah'), ('Beyaz', 'Beyaz'), ('Mavi', 'Mavi'), ('Lacivert', 'Lacivert'), ('Kahverengi', 'Kahverengi'), ('Camel', 'Camel'), ('Yesil', 'Yesil'), ('Haki', 'Haki'), ('Turuncu', 'Turuncu'), ('Pembe', 'Pembe'), ('Kirmizi', 'Kirmizi'), ('Bordo', 'Bordo'), ('Mor', 'Mor'), ('Sari', 'Sari'), ('Gri', 'Gri'), ('Antrasit', 'Antrasit'), ('Multicolor', 'Multicolor')], max_length=100, null=True)),
                ('karisim', models.CharField(blank=True, choices=[('Akrilik', 'Akrilik'), ('Alpaka', 'Alpaka'), ('Angora', 'Angora'), ('Kasmir', 'Kasmir'), ('Pamuk', 'Pamuk'), ('Elastan', 'Elastan'), ('Keten', 'Keten'), ('Polyamid', 'Polyamid'), ('Polyester', 'Polyester'), ('Ipek', 'Ipek'), ('Moher', 'Moher'), ('Yun', 'Yun'), ('Viskon', 'Viskon')], max_length=100, null=True)),
                ('agirlik', models.CharField(blank=True, choices=[('0-200 g/mtul', '0-200 g/mtul'), ('201-400g/mtul', '201-400g/mtul'), ('401-600g/mtul', '401-600g/mtul'), ('600+ g/mtul', '600+ g/mtul')], max_length=100, null=True)),
                ('siparis', models.CharField(blank=True, choices=[('1-100', '1-100 '), ('101-300', '101-300'), ('301-500', '301-500'), ('500+', '500+')], max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'ürünler',
            },
        ),
        migrations.CreateModel(
            name='Upholstery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='başlık')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='ingilizce başlık')),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='rusça başlık')),
                ('img', sorl.thumbnail.fields.ImageField(upload_to='dosemelik', verbose_name='resim')),
                ('renk', models.CharField(blank=True, choices=[('Bej', 'Bej'), ('Siyah', 'Siyah'), ('Beyaz', 'Beyaz'), ('Mavi', 'Mavi'), ('Lacivert', 'Lacivert'), ('Kahverengi', 'Kahverengi'), ('Camel', 'Camel'), ('Yesil', 'Yesil'), ('Haki', 'Haki'), ('Turuncu', 'Turuncu'), ('Pembe', 'Pembe'), ('Kirmizi', 'Kirmizi'), ('Bordo', 'Bordo'), ('Mor', 'Mor'), ('Sari', 'Sari'), ('Gri', 'Gri'), ('Antrasit', 'Antrasit'), ('Multicolor', 'Multicolor')], max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Döşemelikler',
            },
        ),
    ]
