# Generated by Django 2.2 on 2020-01-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='agirlik',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='desen',
            field=models.CharField(blank=True, choices=[('ekose', 'ekose'), ('Etnik', 'Etnik'), ('Geometrik', 'Geometrik'), ('Baliksirti', 'Baliksirti'), ('Kazayagi', 'Kazayagi'), ('Duz', 'Duz'), ('Cizgi', 'Cizgi'), ('Tweed', 'Tweed')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='karisim',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='renk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
