# Generated by Django 4.2.24 on 2025-09-18 19:41

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ürün Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='products/', verbose_name='Ürün Resmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organik Ürün',
                'verbose_name_plural': 'Organik Ürünler',
                'ordering': ['-created_at'],
            },
        ),
    ]
