# Generated by Django 2.2.12 on 2020-11-21 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='upholstery',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='upholstery',
            name='name_ru',
        ),
    ]
