# Generated by Django 2.2.12 on 2020-11-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upholstery',
            name='price',
            field=models.IntegerField(default=1, verbose_name='fiyat'),
            preserve_default=False,
        ),
    ]
