# Generated by Django 2.2 on 2020-01-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200111_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='siparis',
            field=models.CharField(blank=True, choices=[('1-100', '1-100 '), ('101-300', '101-300'), ('301-500', '301-500'), ('500+', '500+')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='agirlik',
            field=models.CharField(blank=True, choices=[('0-200 g/mtul', '0-200 g/mtul'), ('201-400g/mtul', '201-400g/mtul'), ('401-600g/mtul', '401-600g/mtul'), ('600+ g/mtul', '600+ g/mtul')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='karisim',
            field=models.CharField(blank=True, choices=[('Akrilik', 'Akrilik'), ('Alpaka', 'Alpaka'), ('Angora', 'Angora'), ('Kasmir', 'Kasmir'), ('Pamuk', 'Pamuk'), ('Elastan', 'Elastan'), ('Keten', 'Keten'), ('Polyamid', 'Polyamid'), ('Polyester', 'Polyester'), ('Ipek', 'Ipek'), ('Moher', 'Moher'), ('Yun', 'Yun'), ('Viskon', 'Viskon')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='renk',
            field=models.CharField(blank=True, choices=[('Bej', 'Bej'), ('Siyah', 'Siyah'), ('Beyaz', 'Beyaz'), ('Mavi', 'Mavi'), ('Lacivert', 'Lacivert'), ('Kahverengi', 'Kahverengi'), ('Camel', 'Camel'), ('Tesil', 'Tesil'), ('Haki', 'Haki'), ('Turuncu', 'Turuncu'), ('Pembe', 'Pembe'), ('Kirmizi', 'Kirmizi'), ('Bordo', 'Bordo'), ('Mor', 'Mor'), ('Sari', 'Sari'), ('Gri', 'Gri'), ('Antrasit', 'Antrasit'), ('Multicolor', 'Multicolor')], max_length=100, null=True),
        ),
    ]
