# Generated by Django 2.2.12 on 2020-11-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201121_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='ingilizce başlık'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='rusça başlık'),
        ),
        migrations.AddField(
            model_name='upholstery',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='ingilizce başlık'),
        ),
        migrations.AddField(
            model_name='upholstery',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='rusça başlık'),
        ),
    ]
