# Generated by Django 2.2 on 2020-03-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200111_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upholstery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='')),
                ('renk', models.CharField(blank=True, choices=[('Bej', 'Bej'), ('Siyah', 'Siyah'), ('Beyaz', 'Beyaz'), ('Mavi', 'Mavi'), ('Lacivert', 'Lacivert'), ('Kahverengi', 'Kahverengi'), ('Camel', 'Camel'), ('Tesil', 'Tesil'), ('Haki', 'Haki'), ('Turuncu', 'Turuncu'), ('Pembe', 'Pembe'), ('Kirmizi', 'Kirmizi'), ('Bordo', 'Bordo'), ('Mor', 'Mor'), ('Sari', 'Sari'), ('Gri', 'Gri'), ('Antrasit', 'Antrasit'), ('Multicolor', 'Multicolor')], max_length=100, null=True)),
                ('siparis', models.IntegerField()),
            ],
        ),
    ]
