# Generated by Django 2.2 on 2020-03-01 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_upholstery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upholstery',
            name='price',
        ),
        migrations.RemoveField(
            model_name='upholstery',
            name='siparis',
        ),
    ]
