# Generated by Django 2.2.12 on 2020-11-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200301_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='renk',
            field=models.CharField(blank=True, choices=[('Bej', 'Bej'), ('Siyah', 'Siyah'), ('Beyaz', 'Beyaz'), ('Mavi', 'Mavi'), ('Lacivert', 'Lacivert'), ('Kahverengi', 'Kahverengi'), ('Camel', 'Camel'), ('Yesil', 'Yesil'), ('Haki', 'Haki'), ('Turuncu', 'Turuncu'), ('Pembe', 'Pembe'), ('Kirmizi', 'Kirmizi'), ('Bordo', 'Bordo'), ('Mor', 'Mor'), ('Sari', 'Sari'), ('Gri', 'Gri'), ('Antrasit', 'Antrasit'), ('Multicolor', 'Multicolor')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='upholstery',
            name='renk',
            field=models.CharField(blank=True, choices=[('Bej', 'Bej'), ('Siyah', 'Siyah'), ('Beyaz', 'Beyaz'), ('Mavi', 'Mavi'), ('Lacivert', 'Lacivert'), ('Kahverengi', 'Kahverengi'), ('Camel', 'Camel'), ('Yesil', 'Yesil'), ('Haki', 'Haki'), ('Turuncu', 'Turuncu'), ('Pembe', 'Pembe'), ('Kirmizi', 'Kirmizi'), ('Bordo', 'Bordo'), ('Mor', 'Mor'), ('Sari', 'Sari'), ('Gri', 'Gri'), ('Antrasit', 'Antrasit'), ('Multicolor', 'Multicolor')], max_length=100, null=True),
        ),
    ]
