# Generated by Django 2.2.12 on 2020-11-19 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20201109_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'ürünler'},
        ),
        migrations.AlterModelOptions(
            name='upholstery',
            options={'verbose_name_plural': 'Döşemelikler'},
        ),
    ]
