# Generated by Django 2.2.12 on 2020-11-20 22:29

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20201119_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.CharField(max_length=200, verbose_name='detay'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=sorl.thumbnail.fields.ImageField(upload_to='urunler', verbose_name='resim'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='isim'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='fiyat'),
        ),
        migrations.AlterField(
            model_name='upholstery',
            name='img',
            field=sorl.thumbnail.fields.ImageField(upload_to='dosemelik', verbose_name='resim'),
        ),
        migrations.AlterField(
            model_name='upholstery',
            name='name',
            field=models.CharField(max_length=100, verbose_name='isim'),
        ),
    ]
