# Generated by Django 2.2 on 2019-12-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='sirket',
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='firma_adi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='firma_bilgisi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='telefon',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
