# Generated by Django 2.2.12 on 2020-11-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191221_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendeduser',
            old_name='firma_bilgisi',
            new_name='isim',
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='soyisim',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
