# Generated by Django 2.2.12 on 2020-11-26 09:24

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', jsonfield.fields.JSONField(default=dict)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('active', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(blank=True, null=True, to='product.Product')),
                ('upholsteries', models.ManyToManyField(blank=True, null=True, to='product.Upholstery')),
            ],
            options={
                'verbose_name': 'Sepet',
                'verbose_name_plural': 'My images',
            },
        ),
    ]
