# Generated by Django 2.2 on 2020-01-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='details',
            field=models.TextField(null=True),
        ),
    ]
