# Generated by Django 2.2 on 2020-01-16 19:02

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='details',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
