# Generated by Django 2.2 on 2020-01-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20200116_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='details',
            field=models.TextField(null=True),
        ),
    ]
