# Generated by Django 2.2 on 2020-03-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200301_0836'),
        ('cart', '0005_auto_20200116_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='upholsteries',
            field=models.ManyToManyField(blank=True, null=True, to='product.Upholstery'),
        ),
    ]
