# Generated by Django 2.2.12 on 2020-11-09 16:17

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cart_upholsteries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='details',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
