# Generated by Django 2.2.12 on 2020-11-17 22:26

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20201109_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='details',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
