# Generated by Django 2.2.12 on 2020-11-19 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20201117_2226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Sepet', 'verbose_name_plural': 'My images'},
        ),
    ]
